import { useEffect, useState } from "react";
import { Screen, SignupData, Task } from "./types";
import { DEMO_TASKS } from "./data";
import { getMVP, saveProfile, toggleTask } from "./api";
import Landing from "./pages/Landing"; import Login from "./pages/Login"; import Signup from "./pages/Signup"; import Home from "./pages/Home"; import Streak from "./pages/Streak"; import Recovery from "./pages/Recovery"; import Exams from "./pages/Exams"; import Plan from "./pages/Plan"; import Chat from "./pages/Chat"; import Profile from "./pages/Profile";
const DEMO_LOGIN_USER:SignupData={name:"دانش‌آموز",major:"ریاضی فیزیک",grade:"دوازدهم (سال کنکور)",examYear:"۱۴۰۶",targetRank:"زیر ۵٬۰۰۰",studyHours:"۳ تا ۴ ساعت",testExams:["قلم‌چی","گاج"]};
const NAV_ITEMS:[Screen,string][]=[["home","خانه"],["streak","استریک"],["recovery","ریکاوری"],["exams","آزمون‌ها"],["plan","برنامه"],["profile","پروفایل"]];
function Sidebar({screen,nav,dark,toggleDark}:{screen:Screen;nav:(s:Screen)=>void;dark:boolean;toggleDark:()=>void}){return <aside className="hidden md:flex flex-col fixed top-0 right-0 bottom-0 w-[220px] bg-white border-r border-[var(--border)] z-30"><div className="px-5 pt-7 pb-5 border-b border-[var(--border)]"><p className="font-display text-2xl">بوم</p><p className="text-[10px] text-[var(--muted-2)]">برنامه‌ریز کنکور</p></div><nav className="flex-1 p-3 space-y-1">{NAV_ITEMS.map(([s,l])=><button key={s} onClick={()=>nav(s)} className={`w-full px-4 py-3 rounded-2xl text-right font-semibold text-sm ${screen===s?"bg-[var(--accent-soft)] text-[var(--accent)]":"text-[var(--muted)] hover:bg-[var(--surface-2)]"}`}>{l}</button>)}</nav><button onClick={toggleDark} className="m-4 p-3 rounded-2xl bg-[var(--surface-2)]">{dark?"حالت روشن":"حالت تاریک"}</button><button onClick={()=>nav("chat")} className="m-4 mt-0 py-3 rounded-2xl bg-[var(--text)] text-white font-bold">گفتگو با بوم AI</button></aside>}
function Shell({children,screen,nav,dark,toggleDark}:{children:React.ReactNode;screen:Screen;nav:(s:Screen)=>void;dark:boolean;toggleDark:()=>void}){const hide=["landing","login","signup"].includes(screen);return <div dir="rtl" className="min-h-screen bg-[var(--page-bg)]">{!hide&&<Sidebar screen={screen} nav={nav} dark={dark} toggleDark={toggleDark}/>}<div className={`min-h-screen ${!hide?"md:mr-[220px]":""}`}><div className="w-full max-w-[430px] mx-auto md:max-w-none min-h-screen bg-[var(--surface)]">{children}</div></div></div>}
export default function App(){const[screen,setScreen]=useState<Screen>("landing");const[dark,setDark]=useState(()=>localStorage.getItem("boom-theme")==="dark");const[userData,setUserData]=useState<SignupData|null>(null);const[tasks,setTasks]=useState<Task[]>(DEMO_TASKS);const[showGate,setShowGate]=useState(false);const[interactions,setInteractions]=useState(0);const nav=(s:Screen)=>{setScreen(s);window.scrollTo(0,0)};useEffect(()=>{document.documentElement.classList.toggle("dark",dark)},[dark]);useEffect(()=>{if(localStorage.getItem("boom-token"))getMVP().then(d=>{setUserData(d.profile);setTasks(d.tasks as unknown as Task[]);nav("home")}).catch(()=>localStorage.removeItem("boom-token"))},[]);async function completeSignup(data:SignupData){await saveProfile(data);setUserData(data);nav("home")}const p={nav};return <Shell screen={screen} nav={nav} dark={dark} toggleDark={()=>setDark(x=>{localStorage.setItem("boom-theme",!x?"dark":"light");return!x})}>{screen==="landing"&&<Landing{...p}/>} {screen==="login"&&<Login{...p} onLogin={()=>nav("home")}/>} {screen==="signup"&&<Signup{...p} onComplete={completeSignup}/>} {screen==="home"&&userData&&<Home{...p} userData={userData} tasks={tasks} setTasks={setTasks} onInteract={()=>setInteractions(x=>x+1)} showGate={showGate} onGateAccept={()=>{setShowGate(false);nav("profile")}} onGateDismiss={()=>setShowGate(false)}/>} {screen==="streak"&&<Streak{...p}/>} {screen==="recovery"&&<Recovery{...p}/>} {screen==="exams"&&<Exams{...p}/>} {screen==="plan"&&<Plan{...p}/>} {screen==="chat"&&<Chat{...p} userData={userData}/>} {screen==="profile"&&<Profile{...p} userData={userData}/>} {screen==="home"&&!userData&&<Landing{...p}/>}</Shell>}
